Features/khmic/routetesting
daniel-rocha/azure-sdk-for-java pull request #8
Opened 2022-03-15 11:58 UTC by khmic5

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

2022-03-18 09:01 UTC, daniel-rocha requested changes
You need to rebase this branch to remove Traffic from it, since it's already been merged. This should reduce the size of this PR. 

In the future, one PR per module would be nice to avoid reviewing different modules with different context. But I will review this one once it's rebased and the Traffic changes are resolved.

2022-03-22 13:02 UTC, daniel-rocha requested changes
Well done! Just a few observations about lat/lon that you need to re-test and revalidate.

2022-03-22 13:02 UTC, daniel-rocha commented on sdk/maps/azure-maps-route/src/main/java/com/azure/maps/route/implementation/helpers/Utility.java
> +                return Arrays.asList(position.getLongitude(), position.getLatitude());
This seems like a good catch given the composition of GeoJsonMultiPoint. Have you verified that it produces the right tests, as compared to the example provided on teh documentation?

2022-03-22 13:02 UTC, daniel-rocha commented on sdk/maps/azure-maps-route/src/main/java/com/azure/maps/route/implementation/helpers/Utility.java
> +            .map(item -> item.getLongitude() + "," + item.getLatitude())
Same question as above. Verified with testing?

2022-03-22 13:02 UTC, daniel-rocha commented on sdk/maps/azure-maps-route/src/test/java/com/azure/maps/route/RouteAsyncClientTest.java
> +        new GeoPoint(13.42937, 52.50931)));
13.42 is longitude here,
52.509 is latitude.

In the method toRouteQueryString() above you are returning "longitude, latitude", that would translate to "13.42, 52.509" which not the correct coordinate, since it lands in the middle of the sea. Can you please re-validate the logic?

2022-03-22 13:02 UTC, daniel-rocha commented on sdk/maps/azure-maps-route/src/main/java/com/azure/maps/route/implementation/helpers/Utility.java
> +            .map(item -> item.getLongitude() + "," + item.getLatitude())
Reviewing the test, I don't think this is right. Please re-verify. From the example below in the test, this would 13.042, 52.5059, which is not the right coordinate.

2022-03-22 13:02 UTC, daniel-rocha commented on sdk/maps/azure-maps-route/src/test/java/com/azure/maps/route/RouteAsyncClientTest.java
> +        new GeoPoint(13.42937, 52.50931)));
All these should be re-verified.

2022-03-22 13:02 UTC, daniel-rocha commented on sdk/maps/azure-maps-route/src/test/java/com/azure/maps/route/RouteClientTest.java
> +        matrixQuery.setOrigins(origins);
Same comments as above.

2022-03-22 13:02 UTC, daniel-rocha commented on sdk/maps/azure-maps-route/src/test/resources/getroutedirections.json
> +                            "latitude": 52.5093,
Again, from reading the code it seems like toRouteQueryString will return "lon,lat:lon,lat", which should not match this result here.

2022-03-22 23:15 UTC, khmic5 commented on sdk/maps/azure-maps-route/src/test/java/com/azure/maps/route/RouteAsyncClientTest.java
> +        new GeoPoint(13.42937, 52.50931)));
Here it is not using the method toRouteQueryString(), it is directly instantiating a new GeoPoint which takes in longitude then latitude so it is (52.509, 13.42) where 52.509 is latitude and 13.42 is longitude - this point lands in Berlin, Germany

2022-03-23 08:48 UTC, daniel-rocha approved these changes

2022-03-23 08:48 UTC, merged